### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by ThePranu** [linhub15/bookthatspace#3]
Tried signing up with google on chrome and edge. I was unable to login. It brings me back to login page.

**Comment by linhub15** [comment]
Reproduced with Chrome 121.0.6167.184 (Official Build) (64-bit)
Reproduced with Safari 16.6 (18615.3.12.11.2)
Unable to reproduce with Firefox 123.0 (64-bit)

It's an issue with https://github.com/supabase/supabase-js `#936`
Workaround, downgrade the gotrue version.
